In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset = dataset.drop(columns=['User ID'])

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0         True
1     35            20000          0         True
2     26            43000          0        False
3     27            57000          0        False
4     19            76000          0         True
..   ...              ...        ...          ...
395   46            41000          1        False
396   51            23000          1         True
397   50            20000          1        False
398   36            33000          0         True
399   49            36000          1        False

[400 rows x 4 columns]

In [7]:
x=dataset[['Age', 'EstimatedSalary', 'Gender_Male']]
y=dataset[['Purchased']]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=11)

In [15]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(x, y)

C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [16]:
y_pred=clf.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)
print(clf_report)

[[49  4]
 [ 5 22]]
              precision    recall  f1-score   support

           0       0.91      0.92      0.92        53
           1       0.85      0.81      0.83        27

    accuracy                           0.89        80
   macro avg       0.88      0.87      0.87        80
weighted avg       0.89      0.89      0.89        80